### ISSUE TITLE
[Bug Report] Can't run the 4-bit quantized Llama-2 demo

### ISSUE THREAD

**Issue by atlaie** [TransformerLensOrg/TransformerLens#575]
**Describe the bug**

I tried to reproduce the [4-bit quantized Llama-2 demo](https://github.com/coolvision/TransformerLens/blob/llama_4bit/demos/Llama_quantized.ipynb) provided by @coolvision  in my own [Colab session](https://colab.research.google.com/drive/1piEbyqjfJGyyK6C-6DhR5wlmWE5S5Hze?usp=sharing), but I couldn't. I get:

_ValueError: Blockwise quantization only supports 16/32-bit floats, but got torch.uint8_

**System Info**
As can be seen in that Colab, I installed all dependencies as:

```python
!pip install poetry
!poetry config virtualenvs.in-project true
!poetry init
!poetry source add --priority=supplemental torch https://download.pytorch.org/whl/cu118
!poetry add torch==2.1.1+cu118 --source torch
!pip install -i https://pypi.org/simple/ bitsandbytes
!pip install accelerate
!pip install git+https://github.com/neelnanda-io/TransformerLens.git
```

What am I missing?

Thanks for the great work!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/neelnanda-io/TransformerLens/issues) in the repo (**required**)

**Comment by StarConnor** [comment]
@atlaie I have the same issue. I have checked the transformer_lens version and it doesn't work. Have you solved it?

**Comment by winnieyangwannan** [comment]
@StarConnor  and @atlaie , I have the same issue. Has any of you solved it?

**Comment by bryce13950** [comment]
I will see if I can find a solution for this tomorrow.

**Comment by bryce13950** [comment]
Unfortunately, this is going to take a little bit longer to resolve. It seems like this whole demo needs a full relook. I am getting issues that have not been brought up here. I am going to take a moment to go through the whole notebook, and make sure it is brought up to date. I will have more time to look at it tomorrow, and hopefully that will be enough time to figure out what is going on here. I will keep you all in the loop with what is happening.

**Comment by winnieyangwannan** [comment]
Thank you so much @bryce13950  for your time and efforts! Really appreciated!

**Comment by bryce13950** [comment]
Hey all. Little update here. I have been pulled away to work through some other bugs on the larger base. Hopefully that is wrapped up for the week, and I can focus getting this back up to date for you all. Will make sure to keep you all informed as to progress.

**Comment by bryce13950** [comment]
This has been resolved https://colab.research.google.com/github/TransformerLensOrg/TransformerLens/blob/demos-test-coverage/demos/LLaMA2_GPU_Quantized.ipynb#scrollTo=urpZu9jECUsT. It will be in main tomorrow.

**Comment by winnieyangwannan** [comment]
> This has been resolved https://colab.research.google.com/github/TransformerLensOrg/TransformerLens/blob/demos-test-coverage/demos/LLaMA2_GPU_Quantized.ipynb#scrollTo=urpZu9jECUsT. It will be in main tomorrow.

@bryce1395 Thank you so much for taking your time! Thanks a ton! You are great!

**Comment by atlaie** [comment]
Thank you so much for the time and effort!

**Comment by Gaverfraxz** [comment]
Hey, the colab is still not working for me. I'm running every cell as is, while using a T4 environment. I get:
```ImportError: Using `bitsandbytes` 8-bit quantization requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes: `pip install -i https://pypi.org/simple/ bitsandbytes```. 
Is this just me?
